# This file was generated by GoReleaser. DO NOT EDIT.
class Timesum < Formula
  desc "A simple terminal UI for calculating time worked, written in Go"
  homepage "https://github.com/eriklupander/timesum/"
  url "https://github.com/eriklupander/timesum/releases/download/0.0.4/timesum_0.0.4_Darwin_x86_64.tar.gz"
  version "0.0.4"
  sha256 "d0694d9513704aff29cab3c0d247cf0f0280b466d375636253151fd67cf25715"

  def install
    bin.install "timesum"
  end
end
