# This file was generated by GoReleaser. DO NOT EDIT.
class Timesum < Formula
  desc "A simple terminal UI for calculating time worked, written in Go"
  homepage "https://github.com/eriklupander/timesum"
  url "https://github.com/eriklupander/timesum/releases/download/v0.1.2/timesum_0.1.2_Darwin_x86_64.tar.gz"
  version "0.1.2"
  sha256 "d9507525015dd3d4e27cdd2012e4e699b6bd6cac8f1c054418289aced6d71542"

  def install
    bin.install "timesum"
  end
end
